### ISSUE TITLE
AMQJS0013E

### ISSUE THREAD

**Issue by MrLrx** [estbeetoo/cordova-plugin-mqtt-pahojs#2]
@aborovsky 
 hi，can you help me？
https://user-images.githubusercontent.com/32866459/62263947-83046f00-b450-11e9-8e03-f4e4172dd9f1.png

https://user-images.githubusercontent.com/32866459/62263921-741dbc80-b450-11e9-85d0-0bfe143ae75e.png

**Comment by aborovsky** [comment]
Hi, @MrLrx! Host must be fully qualified uri with `ws://` or `wss://` protocol: `ws://mqt.onenet.hk.chinamobile.com:6002`.

Let me know if URI solved your problem.

**Comment by MrLrx** [comment]
@aborovsky oh,no!It reminds me 
![image](https://user-images.githubusercontent.com/32866459/62277292-6e3bd180-b478-11e9-9541-18187237c283.png)

**Comment by MrLrx** [comment]
@aborovsky Can I use TCP protocol?

**Comment by aborovsky** [comment]
Current lib based on Paho, pure JS implementation of MQTT client. So it only support MQTT over WebSockets. To communicate with native MQTT protocol (over TCP) inside of Cordova, use appropriate plugin: https://github.com/arcoirislabs/cordova-plugin-mqtt

**Comment by MrLrx** [comment]
I tried, but he couldn't push data streams.

**Comment by aborovsky** [comment]
What's exactly MQTT streams stands for?

**Comment by MrLrx** [comment]
@aborovsky 
![image](https://user-images.githubusercontent.com/32866459/62337361-e51fab80-b506-11e9-8111-29581accb986.png) Hi,I tried to publish data stream to this,but i get the error
![image](https://user-images.githubusercontent.com/32866459/62337451-447dbb80-b507-11e9-9b1c-10fc44a1825f.png)
